### ISSUE TITLE
Instructions for using without import fail on Python 3.10

### ISSUE THREAD

**Issue by ssteinerx** [samuelcolvin/python-devtools#102]
https://python-devtools.helpmanual.io/usage/#usage-without-import

Suggests the following snippet:

```python
    __builtins__['debug'] = debug
```

In python 3.10 (at least, only version tried), referencing __builtins__ directly gives "TypeError: 'module' object is not subscriptable"

__builtins__.__dict__, however, is subscriptable.

That figuring out where sitecustomize.py (or usercustomize.py) actually can be put so it gets properly executed on startup on a multi-python and/or brew (linuxbrew) system is an absolute nightmare is a different issue and not one I'd expect python-devtools to address particularly.

**Comment by samuelcolvin** [comment]
Interesting, I'll look back at what I have. 

> That figuring out where sitecustomize.py (or usercustomize.py) actually can be put so it gets properly executed on startup on a multi-python and/or brew (linuxbrew) system is an absolute nightmare is a different issue and not one I'd expect python-devtools to address particularly.

Agreed, printing `sys.path` can help a lot, we should add this to the docs too.

**Comment by alexmojaki** [comment]
https://stackoverflow.com/questions/11181519/whats-the-difference-between-builtin-and-builtins

`__builtins__` can be either the module or the dict in the same python version, depending on context.

**Comment by samuelcolvin** [comment]
Maybe we could add `devtools.install()` to take care of this?

**Comment by alexmojaki** [comment]
That would fit well with https://github.com/gruns/icecream#import-tricks and https://github.com/alexmojaki/snoop#install

But you can also just change the recommendation to `import builtins; builtins.debug = debug` and that should work consistently, since this is Python 3 only.

**Comment by samuelcolvin** [comment]
See #108, I've added a tiny `install` CLI.
