### ISSUE TITLE
Not Getting Colored Output in jupyter notebook

### ISSUE THREAD

**Issue by jiaulislam** [samuelcolvin/python-devtools#119]
Hi, I understand it's not an issue. But I couldn't find any place to write. Is there any-way to get  colored output in jupyter-notebook output cell.

![image](https://user-images.githubusercontent.com/54698236/207789219-65c96044-e01e-47e6-a110-66b18a4bca3c.png)

**Comment by samuelcolvin** [comment]
Is pygments installed?
