### ISSUE TITLE
how __pretty__ works

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/python-devtools#78]
I'll describe fully how the `__pretty__` unofficial dunder method is used by devtools on the remove off chance that @willmcgugan might adopt a similar thing in [rich](https://github.com/willmcgugan/rich).

This approach seems to work but is completely unofficial and wasn't developed in collaboration with others, so might require changes. I'd be very happy to support a changes to this, particularly if it can be somewhat backwards compatible.

### The Idea

Provide a way for objects to describe how they should be displayed in "rich" (no pun intended) contexts, without moving all the logic of pretty printing into the object.

### The implementation

objects which want to be pretty printed include a `__pretty__` method with takes as arguments:
* `fmt` a callable which takes one argument (usage described below)
* extra `**kwargs` in case we want to pass more things to the method later

It yields (or returns a list of) any of the following:
* string, in which case that string is printed on the current line and the current indentation
* int, in which case:
  * `1` means increase the indent by one level (4 spaces, 2 spaces, 1 tab, whatever you want it to mean)
  * `-1` means decrease the indent by one level
  * `0` means new line, same indent
  * I think other numbers can be used to increase or decrease the indent more (e.g. 2 -> increase by two levels), but I can't remember if this is actually implemented, it's generally not needd
*  the result of `fmt(<whatever>)` in which case the application calling `__pretty__` can decide how to render the argument to `fmt()`. This is useful for recursive pretty printing - e.g. a custom type of list doesn't need to know how to render all it's values.

### An example

Here' is the `__pretty__` method from [the reusable `Representation` method in pydantic](https://github.com/samuelcolvin/pydantic/blob/13a5c7d676167b415080de5e6e6a74bea095b239/pydantic/utils.py#L372-L385) with more comments:

```py
    def __pretty__(self, fmt: Callable[[Any], Any], **kwargs: Any) -> Generator[Any, None, None]:
        # show the name of the class together with an opening bracket so it looks a bit like a instance definition:
        yield self.__repr_name__() + '('
        # new line and increase the indent
        yield 1
        for name, value in self.__repr_args__():
            # if this class wants to show name value pairs, show '<name>=`
            if name is not None:
                yield name + '='
            # render the value, devtools (or any tool calling this) can decide how to display the value
            yield fmt(value)
            # add a comma to the end of the line to keep it looking like an instance definition
            yield ','
            # new line without a change of indent
            yield 0
        # decrease indent, no extra new line
        yield -1
        # closing bracket to keep it looking a bit like python
        yield ')'
```

with `self.__repr_name__() --> 'TheName'` and `self.__repr_args__() --> [('x', 1), ('y', 2), (None, 3)]`, it might display

```
TheName(
    x=1,
    y=2
    3,
)
```

**Comment by samuelcolvin** [comment]
But the whole idea here is that the object can decide how it wants to show it's members.

So it might do

```
<
    x --> 1
    y --> 2
    --> 3
/>
```

That's perfectly fine as per this mini-spec.

**Comment by willmcgugan** [comment]
Thanks for the info. It looks like a straightforward solution.

Would this protocol allow for nested structures? i.e. if one of the values also has a `__pretty__` ?

I was thinking that if there is enough space, Rich would print objects on one line. i.e. to use your example:

```python
TheName(x=1, y=2, 3)
```

The pretty printer in Rich does something similar with data structures.

I could implement this for Pydantic by checking for `__repr_name__` and `__repr_args__`, which strikes me as a super simple solution for an object define how it should pretty print. I think `__pretty__` probably serves the same purpose as [`__rich__`](https://rich.readthedocs.io/en/stable/protocol.html) in Rich. It's less of a repr, and more of a mechanism to completely customize how an object prints.

I believe iPython also has a similar protocol for objects to specify how they are pretty printed. I should research that first. Perhaps we can come up with something that satisfies all projects.

Thoughts?

**Comment by samuelcolvin** [comment]
> Would this protocol allow for nested structures? i.e. if one of the values also has a __pretty__ ?

yes absolutely, that's what `fmt()` is for, it takes care of all the display logic for the object passed to it, that includes calling `__pretty__` on that object or objects with it.

> I was thinking that if there is enough space, Rich would print objects on one line. i.e. to use your example:

That's fine, I guess the integer values yielded from `__pretty__` can be optional. You could think of them as "new thing" rather than "new line".

> I think __pretty__ probably serves the same purpose as __rich__

Yes, more or less. One big difference is that devtools doesn't allow highlighting/ansi colors to be controlled by the object, instead it just runs the result through pygments. Ugly and slow, but mostly works pretty well). I would also argue that devtools' approach works better for heavily nested objects, take a look at the somewhat contrived example at the end.

> Perhaps we can come up with something that satisfies all projects.

I would love this. I've commented a few times on python-ideas proposing something similar or supporting others who've proposed similar, the problem is:
* there's no nice public record of python-ideas that google really indexes, so it's lost almost immediately
* The dominant attitude on python-ideas is "how can we shit on all ideas from names we don't know", thus the suggestions got immediately shitcanned.

**Somewhat contrived example:**

```py
from dataclasses import dataclass, asdict
from datetime import datetime
from typing import List, Dict, Set

from pydantic import BaseModel

@dataclass
class CustomRender:
    x: int
    y: Set[int]

    def __pretty__(self, fmt, **kwargs):
        yield '<CustomRender'
        yield 1
        for k, v in asdict(self).items():
            yield f'<{k} '
            yield fmt(v)
            yield '>'
            yield 0
        yield -1
        yield '/>'

class Foobar(BaseModel):
    id: int = 5
    name = 'John Doe'
    signup_ts: datetime
    friends: List[int]
    foobar: Dict[str, List[List[int]]]
    cr: CustomRender


f = Foobar(signup_ts=datetime.now(), friends=[1, 2, 3], foobar={'x': [[4, 3, 2]]}, cr={'x': 123, 'y': [4, 4, 3, 2]})

debug(f)
```
outputs:
![image](https://user-images.githubusercontent.com/4039449/104809982-8678eb00-57e9-11eb-97f8-ad8f614ce95c.png)

**Comment by samuelcolvin** [comment]
hi @willmcgugan, out of interest, did you end up using this?

**Comment by willmcgugan** [comment]
I didn't, no. I considered it, but it didn't quite fit with the [pretty repr system](https://rich.readthedocs.io/en/latest/pretty.html#rich-repr-protocol) I came up with. Although it is really quite similar to your `__pretty__` protocol.

**Comment by samuelcolvin** [comment]
Shame, thanks for letting me know.
